### ISSUE TITLE
Project has invalid dependencies.

### ISSUE THREAD

**Issue by Brianelvio** [heroiclabs/unity-sampleproject#12]
Hi there,

There seems to be an issue with the package on the repository.
Unity seems to be unable to import it.

Unity 2020.3.0f1

manifest.json:
`"com.heroiclabs.nakama-unity": "https://github.com/heroiclabs/nakama-unity.git?path=/Packages/Nakama#efc3d92182f1c00f26cc5a3493fc2406abd01931",`

![image](https://user-images.githubusercontent.com/4085200/111994694-5535d780-8b18-11eb-8145-3411414ebfeb.png)

**Comment by lugehorsam** [comment]
Hey @Brianelvio thanks for catching this -- we've now fixed it.
