### ISSUE TITLE
Where to add server IP?

### ISSUE THREAD

**Issue by bkrajendra** [heroiclabs/unity-sampleproject#13]
How to use my Nakama server hosted on another PC.
Nowhere its mentioned about Nakama server IP.
Instruction straightway talks about open and run. How it's supposed to know about which server to connect.?

Please help!

**Comment by novabyte** [comment]
@bkrajendra The server IP is not mentioned because it depends on where you host the server and how your local network is set up if you've hosted the server in a LAN environment with development.

Please ask these questions on the forums: https://forum.heroiclabs.com. Thanks 🙏

**Comment by bkrajendra** [comment]
HI @novabyte 
Thanks for the quick reply.
I understand that the IP setting might change as per the environment.
Don't you think it's important for new explorers to at least be able to run this sample with basic understanding?

What I learned from few tutorials is that you need to provide a server IP to the Nakama client.
Mostly for a sample project, this should be something which is a configuration/settings which can be located somewhere from where it can be changed as per requirement.

The very first thing after installing the Nakama server and starting this project needs is a server IP, without which we can not test the code. And because server IP can not be predicted makes it a key reason to make it configurable.!

I believe a working sample is the first step towards growing interest among any newcomer. 😊

And to make it working need to dig up the code and change a line in ```Scene01MainMenuController.cs```

```
var client = new Client("http", "10.1.25.5", 7350, "mysecret", UnityWebRequestAdapter.Instance);

```
It will be great if this above line can be made part of the documentation in Readme.

On a positive note, it was a good learning curve to understand code and then find the line to change. ✌✌

Nakama is really an awesome project!

Thanks Again!👍👍

**Comment by lugehorsam** [comment]
Hey @bkrajendra that's a good call to add that line to the documentation. Will do.
