### ISSUE TITLE
Server function "load_user_cards" seems to be missing

### ISSUE THREAD

**Issue by ns2808** [heroiclabs/unity-sampleproject#18]
I just tried playing Pirate Panic in the editor and I got the following error:

Could not load user cards: RPC function not found at line 372 of CardsMenuUI.cs

Has anyone been able to click on the "Cards" button? Also, when I build the game and run both instances to be able to join a Battle there are no cards loading so similar issue I guess.

**Comment by novabyte** [comment]
@ns2808 can you confirm that you loaded the server modules as part of the start of the server before you ran the Unity project?

**Comment by ns2808** [comment]
@novabyte Hi Chris, thank you for getting back to me on this. I didn't actually so I'm sure if I do it properly it will work fine now.
