### ISSUE TITLE
How to use this project on the same IP / machine ?

### ISSUE THREAD

**Issue by louis030195** [heroiclabs/unity-sampleproject#3]
I tried this great project but i can't really try the multiplayer features on the same machine ?

![Peek 2019-05-31 11-49](https://user-images.githubusercontent.com/25003283/58697782-45c12980-839a-11e9-8854-001201c13024.gif)

Thanks for the help !

**Comment by zyro** [comment]
Can you also share the entire server logs in text format please?

**Comment by louis030195** [comment]
I followed the "getting started"

> Starting postgres ... 
Starting postgres ... done
Recreating nakama2 ... 
Recreating nakama2 ... done
Attaching to postgres, nakama2
nakama2     | + /nakama/nakama migrate up --database.address postgres@postgres:5432/nakama
postgres    | LOG:  database system was shut down at 2019-05-31 09:53:07 UTC
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.736Z","msg":"Database connection","dsn":"postgres@postgres:5432/nakama"}
postgres    | LOG:  MultiXact member wraparound protections are now enabled
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.740Z","msg":"Database information","version":"PostgreSQL 9.6.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"}
postgres    | LOG:  database system is ready to accept connections
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.741Z","msg":"Using existing database","name":"nakama"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.747Z","msg":"Successfully applied migration","count":0}
nakama2     | + exec /nakama/nakama --name nakama1 --database.address postgres@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200
nakama2     | {"level":"warn","ts":"2019-05-31T11:16:46.785Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.username"}
nakama2     | {"level":"warn","ts":"2019-05-31T11:16:46.785Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.password"}
nakama2     | {"level":"warn","ts":"2019-05-31T11:16:46.785Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"socket.server_key"}
nakama2     | {"level":"warn","ts":"2019-05-31T11:16:46.785Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"session.encryption_key"}
postgres    | LOG:  autovacuum launcher started
nakama2     | {"level":"warn","ts":"2019-05-31T11:16:46.785Z","msg":"WARNING: insecure default parameter value, change this for production!","param":"runtime.http_key"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.785Z","msg":"Nakama starting"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.785Z","msg":"Node","name":"nakama1","version":"2.4.1+05df019a","runtime":"go1.12","cpu":8}
postgres    | ERROR:  database "nakama" already exists
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.785Z","msg":"Data directory","path":"/nakama/data"}
postgres    | STATEMENT:  CREATE DATABASE "nakama"
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.785Z","msg":"Database connections","dsns":["postgres@postgres:5432/nakama"]}
nakama2     | {"level":"debug","ts":"2019-05-31T11:16:46.785Z","msg":"Complete database connection URL","raw_url":"postgresql://postgres@postgres:5432/nakama?sslmode=disable"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.788Z","msg":"Database information","version":"PostgreSQL 9.6.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.791Z","msg":"Initializing leaderboard rank cache"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.791Z","msg":"Leaderboard rank cache initialization completed successfully","cached":[],"skipped":[]}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.791Z","msg":"Initialising runtime","path":"/nakama/data/modules"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.792Z","msg":"Initialising Go runtime provider","path":"/nakama/data/modules"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.792Z","msg":"Go runtime modules loaded"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.792Z","msg":"Initialising Lua runtime provider","path":"/nakama/data/modules"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Lua runtime modules loaded"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Allocating minimum runtime pool","count":16}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Allocated minimum runtime pool"}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Found runtime modules","count":0,"modules":[]}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Starting Console server for gRPC requests","port":7348}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Starting Console server gateway for HTTP requests","port":7351}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Starting API server for gRPC requests","port":7349}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:46.794Z","msg":"Starting API server gateway for HTTP requests","port":7350}
nakama2     | {"level":"info","ts":"2019-05-31T11:16:47.159Z","msg":"Startup done"}
nakama2     | {"level":"info","ts":"2019-05-31T11:17:23.460Z","msg":"New WebSocket session connected","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","format":0}
nakama2     | {"level":"info","ts":"2019-05-31T11:17:24.772Z","msg":"New WebSocket session connected","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","format":0}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:27.451Z","msg":"Received *rtapi.Envelope_MatchmakerAdd message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","cid":"e9ce146f-3a49-49d8-bb28-51991e246d64","message":{"MatchmakerAdd":{"min_count":2,"max_count":2,"query":"*"}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:27.451Z","msg":"Sending *rtapi.Envelope_MatchmakerTicket message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","envelope":"cid:\"e9ce146f-3a49-49d8-bb28-51991e246d64\" matchmaker_ticket:<ticket:\"8e5dcf81-d954-49eb-88ee-f004b8f63a9e\" > "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.204Z","msg":"Received *rtapi.Envelope_MatchmakerAdd message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","cid":"69721c82-7c83-4837-82e2-42ccca07efc0","message":{"MatchmakerAdd":{"min_count":2,"max_count":2,"query":"*"}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.207Z","msg":"Sending *rtapi.Envelope_MatchmakerTicket message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","envelope":"cid:\"69721c82-7c83-4837-82e2-42ccca07efc0\" matchmaker_ticket:<ticket:\"1b29c04f-ea8d-44f7-adc8-c2b2060f869c\" > "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.328Z","msg":"Received *rtapi.Envelope_MatchJoin message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","cid":"7179ed9c-581a-4eaa-8d24-a68d7f606c79","message":{"MatchJoin":{"Id":{"Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTkzMDE0NzksIm1pZCI6IjEwY2VkZDE0LTUxYTgtNDU0Yi1hYjYzLWRhZWQ5YjlmMzQ5Zi4ifQ.Ww-SIsEpLkYRcXsFBIH8ma2oH_tCs_VXrt60Fwq34lY"}}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.329Z","msg":"Sending *rtapi.Envelope_Match message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","envelope":"cid:\"7179ed9c-581a-4eaa-8d24-a68d7f606c79\" match:<match_id:\"10cedd14-51a8-454b-ab63-daed9b9f349f.\" self:<user_id:\"4ccfa954-6078-4c6a-93c2-1a006c5f7427\" session_id:\"030bea98-30ab-4a4c-9221-dbbd38c95a1e\" username:\"az\" > > "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.329Z","msg":"Processing presence event","joins":1,"leaves":0}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.344Z","msg":"Received *rtapi.Envelope_MatchJoin message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","cid":"4257a40c-cd9b-4736-b413-bcd4170056c6","message":{"MatchJoin":{"Id":{"Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTkzMDE0NzksIm1pZCI6IjEwY2VkZDE0LTUxYTgtNDU0Yi1hYjYzLWRhZWQ5YjlmMzQ5Zi4ifQ.Ww-SIsEpLkYRcXsFBIH8ma2oH_tCs_VXrt60Fwq34lY"}}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.344Z","msg":"Processing presence event","joins":1,"leaves":0}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.344Z","msg":"Sending *rtapi.Envelope_Match message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","envelope":"cid:\"4257a40c-cd9b-4736-b413-bcd4170056c6\" match:<match_id:\"10cedd14-51a8-454b-ab63-daed9b9f349f.\" size:1 presences:<user_id:\"4ccfa954-6078-4c6a-93c2-1a006c5f7427\" session_id:\"030bea98-30ab-4a4c-9221-dbbd38c95a1e\" username:\"az\" > self:<user_id:\"4ccfa954-6078-4c6a-93c2-1a006c5f7427\" session_id:\"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170\" username:\"az\" > > "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.499Z","msg":"Received *rtapi.Envelope_MatchLeave message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","cid":"a24f29e2-8b7d-449f-ace0-e9e6bc35932e","message":{"MatchLeave":{"match_id":"10cedd14-51a8-454b-ab63-daed9b9f349f."}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.500Z","msg":"Sending <nil> message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"f8081d0a-801f-4a8f-9ef2-81e0dcfb2170","envelope":"cid:\"a24f29e2-8b7d-449f-ace0-e9e6bc35932e\" "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.500Z","msg":"Processing presence event","joins":0,"leaves":1}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.625Z","msg":"Received *rtapi.Envelope_MatchLeave message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","cid":"d4877e76-e27c-4bc3-b163-5d0f2291002d","message":{"MatchLeave":{"match_id":"10cedd14-51a8-454b-ab63-daed9b9f349f."}}}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.625Z","msg":"Sending <nil> message","uid":"4ccfa954-6078-4c6a-93c2-1a006c5f7427","sid":"030bea98-30ab-4a4c-9221-dbbd38c95a1e","envelope":"cid:\"d4877e76-e27c-4bc3-b163-5d0f2291002d\" "}
nakama2     | {"level":"debug","ts":"2019-05-31T11:17:29.625Z","msg":"Processing presence event","joins":0,"leaves":1}

**Comment by tkou-nakama** [comment]
Hello @louis030195,

This is an expected result - upon the first connection with the server, your account is created and your unique Device ID is stored in PlayerPrefs so that you don't have to log in every time you launch the game. However, this may cause some inconvinience when testing two clients on the same PC. For this exact scenario, we added a field named "Suffix" in NakamaSessionManager script, which can be edited in inspector. This field adds a suffix to the end of user's Device ID, which enables concurent login.

1. In the hierarchy, find NakamaSessionManager and set the Suffix field's value to something like "a" (without quotation marks).
2. Build the game, launch it, press "Clear Player Prefs" button, then Connect.
3. Back to the editor, in NakamaSessionManager set the Suffix field's value to something different, like "b" (without quotation marks).
4. Build the game in another directory, launch it, press "Clear Player Prefs" button, then Connect.
5. You can now start the battle in both clients

**Comment by louis030195** [comment]
@tkou-nakama Thanks !
I think it could be useful to add these steps in the readme,

solved.
