### ISSUE TITLE
Nakama Dashboard Not showing on my windows 

### ISSUE THREAD

**Issue by PabloMonfort** [heroiclabs/unity-sampleproject#7]
Nakama Dashboard Not showing on my windows Unity nakama server , im using the example Jolly Roger, and i cant access to the nakama dashboard after copy and paste the url of docker of nakama server, btw im using windows 10 home and docker have both postgree and nakama in green, i had to set the - POSTGRES_HOST_AUTH_METHOD=trust propertie in the yml file due i was not able to made this run in otherway , even if i set the postgres a password then nakama was not connecting well so , the question is why i cant access dashboard on all the urls i have tried nothing shows only blank page .
another thing i have seen is that after test with unity and add friends (the reason of why im testing this since the friendship docs seems to leak of documentation that be usefull to me) it worked well the friendships, but when i try to remove of friends , it give me some error of a null reference exception like the unity web request didnt success in the call to it and i guess that have something to do with my problem of the dashboard. thanks in advance.

**Comment by novabyte** [comment]
@PabloMonfort I can't reproduce this issue. Please reopen if you continue to have problems.
